// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanJunction.Data;

#nullable disable

namespace UrbanJunction.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123115025_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Check out the East Side Gallery and RAW Gelände!",
                            CreatedOn = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubcategoryId = 1,
                            Title = "Best Graffiti Spots in Berlin",
                            UserId = "93e5df7b-fb35-46d7-bd8c-7b88546ac77e"
                        },
                        new
                        {
                            Id = 2,
                            Content = "The scene is raw and authentic. Worth experiencing!",
                            CreatedOn = new DateTime(2026, 1, 23, 11, 50, 24, 873, DateTimeKind.Utc).AddTicks(2634),
                            SubcategoryId = 2,
                            Title = "Underground Techno in Detroit",
                            UserId = "93e5df7b-fb35-46d7-bd8c-7b88546ac77e"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Baggy is back. Sneakers are getting chunkier than ever.",
                            CreatedOn = new DateTime(2026, 1, 23, 11, 50, 24, 873, DateTimeKind.Utc).AddTicks(2637),
                            SubcategoryId = 3,
                            Title = "Streetwear Trends for 2025",
                            UserId = "93e5df7b-fb35-46d7-bd8c-7b88546ac77e"
                        });
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Graffiti",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Techno",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Streetwear",
                            TopicId = 3
                        });
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Everything about art",
                            ImageUrl = "/img/art.jpg",
                            Name = "Art"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All genres of music",
                            ImageUrl = "/img/music.jpg",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Trends, streetwear, and design",
                            ImageUrl = "/img/fashion.jpg",
                            Name = "Fashion"
                        });
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.UrbanUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "93e5df7b-fb35-46d7-bd8c-7b88546ac77e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f111692a-0f48-4dee-a11e-8918783842cf",
                            Email = "artlover@urban.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ARTLOVER@URBAN.COM",
                            NormalizedUserName = "EMO",
                            PasswordHash = "AQAAAAIAAYagAAAAEP5IJSqGEzgYEfsgl1bdUcOOns1qMTcUT6EPZi2DLCLQ8HQUi+xKAlVKDwhCiRj3yQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePicturePath = "/images/profile/default-profile.png",
                            SecurityStamp = "fed2c3eb-6ef7-42fa-af70-ec75c83a5f26",
                            TwoFactorEnabled = false,
                            UserName = "Emo"
                        },
                        new
                        {
                            Id = "c3cabab2-2413-4aa6-b3e5-07000f3a069f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6844fa58-f516-4707-b0cc-26b4a76a0ac2",
                            Email = "admin@urban.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@URBAN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEH2nqlqBZqkfUS0E1pUBPDVdZLNrn21eScDsWPDYFFTc/WdTzNRiREH4KbifJVkirQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePicturePath = "/images/profile/default-profile.png",
                            SecurityStamp = "e11cc3da-94c4-474b-9341-6db0045e215d",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "3ad674e3-3797-41ba-b980-9b2e85c32a51",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e3e06a6-d0a6-4119-ae80-4f4b255ccaa5",
                            Email = "musicfan@urban.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MUSICFAN@URBAN.COM",
                            NormalizedUserName = "VALIO",
                            PasswordHash = "AQAAAAIAAYagAAAAEMw1RWZZPVMM8moC37zr07hyp1PtIQuScQjl5eHwOGXjaKZVLz49R3Oz0rTVywORiw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicturePath = "/images/profile/default-profile.png",
                            SecurityStamp = "0cb7c1e7-5c31-4788-85e4-12c83f4ee527",
                            TwoFactorEnabled = false,
                            UserName = "Valio"
                        },
                        new
                        {
                            Id = "c5859895-19f2-47da-ae19-569400ee20d5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef056d48-a707-4482-9064-24404ef2b201",
                            Email = "fashionguru@urban.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FASHIONGURU@URBAN.COM",
                            NormalizedUserName = "MR.YANEV",
                            PasswordHash = "AQAAAAIAAYagAAAAEJCORzIBvxarTWzHR+kDB81GVoYFK6BeOSCIVXiHtsbPjK55LRPjGWd/jtpCoiesJw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicturePath = "/images/profile/default-profile.png",
                            SecurityStamp = "3e6e8e72-0c82-4f1d-b0af-38f7083d055f",
                            TwoFactorEnabled = false,
                            UserName = "Mr.Yanev"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UrbanJunction.Data.Models.UrbanUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UrbanJunction.Data.Models.UrbanUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanJunction.Data.Models.UrbanUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UrbanJunction.Data.Models.UrbanUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Post", b =>
                {
                    b.HasOne("UrbanJunction.Data.Models.Subcategory", "Subcategory")
                        .WithMany("Posts")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanJunction.Data.Models.UrbanUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subcategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.PostImage", b =>
                {
                    b.HasOne("UrbanJunction.Data.Models.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Subcategory", b =>
                {
                    b.HasOne("UrbanJunction.Data.Models.Topic", "Topic")
                        .WithMany("Subcategories")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Post", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Subcategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.Topic", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("UrbanJunction.Data.Models.UrbanUser", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
